# Generated by Django 3.1.6 on 2021-06-28 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(default='')),
                ('fschool', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icategory', models.TextField(default='')),
                ('itype', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Studentinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ggrade_year', models.TextField(default='')),
                ('gaddress', models.TextField(default='')),
                ('gcontactno', models.IntegerField(default='')),
                ('applicant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='JAList.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jstatus', models.TextField(default='')),
                ('jremarks', models.TextField(default='')),
                ('jdate', models.DateTimeField(default='')),
                ('scholarship', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='JAList.scholarship')),
            ],
        ),
        migrations.CreateModel(
            name='School_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcor', models.TextField(default='')),
                ('htor', models.TextField(default='')),
                ('studentinfo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='JAList.studentinfo')),
            ],
        ),
        migrations.AddField(
            model_name='scholarship',
            name='school_Record',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='JAList.school_record'),
        ),
    ]
