# Generated by Django 3.1.6 on 2021-06-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAList', '0003_auto_20210530_0702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school_record',
            old_name='student_Information',
            new_name='studenti',
        ),
        migrations.AlterField(
            model_name='student_information',
            name='gcontactno',
            field=models.IntegerField(default=''),
        ),
    ]
